version: '3'
services:
  newflat-tg-bot:
    image: tg_bot:release
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/opt/bot  # Монтируем текущую директорию хоста внутрь контейнера
    container_name: I_Want_New_Flat_TG_Bot
    restart: always
